<?php

return [

    'SK_ENTERPRISES' => '101',
    'AARAN_INDIA_FASHION' => '102',
    'AARAN_ASSOCIATES' => '103',
    'SK_PRINTERS' => '104',
    'SRI_GANAPATHI_PRINTING_PRESS' => '105',
    'AARAN_INFO_TECH' => '106',

    'PRAPTHIIMPEX' => '107',
    'SMSUPVC' => '108',

    'SARA_SCREENS' => '201',
    'COLOURS_PRINTING' => '202',
    'NEW_AMMAN_PRINTERS' => '203',
    'KGS_PRINTERS' => '204',
    'THIRUMURUGAN_PRINTERS' => '205',
    'KATHIR_PRINTERS' => '206',
    'AJ_PRINTING' => '207',
    'SAIRF_SOURCING' => '208',
    'BEST_PRINT' => '209',

    'VIJAY_GARMENTS' => '301',
    'AMAL_TEX' => '302',
    'ESSA_KNITTING' => '303',
    'ESSA_KNITTING_GARMENT' => '304',
    'FASHION_FABRICS' => '305',
    'A1_IMPEX' => '306',
    'SATHYANARAYANA_GARMENTS' => '307',
    'NEETHU_INDUSTRIES' => '308',
    'MARK_INTERNATIONAL' => '309',
    'SRI_VENKATESWARA_TEXMART' => '310',
    'VETRIVEL_GARMENTS' => '311',
    'ASHWIN_TEX' => '312',

];
